server:
  port: 8888

logging:
  level:
    org:
      example:
        webcontacts: DEBUG

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/contacts
    username: contacts
    password: CONTACTS_password
    hikari:
      schema: contacts_schema
