version: "3"
services:
  postgres:
    image: postgres:12.3
    container_name: webcontacts-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=contacts
    volumes:
      - ./init.sql/:/docker-entrypoint-initdb.d/